[package]
name = "cruzamento_automatico"
version = "0.1.0"
edition = "2021"
authors = ["José Augusto Soares de Moura <josemoura212@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
speedy2d = "2.1.0"
